### ISSUE TITLE
throwing errors in the console

### ISSUE THREAD

**Issue by wormeyman** [patlillis/brackets-show-whitespace-vs#1]
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at loadCommand (file:///C:/Users/ejohnson/AppData/Roaming/Brackets/extensions/user/patlillis.show-whitespace-vs/main.js:264:9)
    at load (file:///C:/Users/ejohnson/AppData/Roaming/Brackets/extensions/user/patlillis.show-whitespace-vs/main.js:300:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at Object.<anonymous> (file:///C:/Users/ejohnson/AppData/Roaming/Brackets/extensions/user/patlillis.show-whitespace-vs/main.js:323:13)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at loadEditorSync (file:///C:/Users/ejohnson/AppData/Roaming/Brackets/extensions/user/patlillis.show-whitespace-vs/main.js:287:9)
    at load (file:///C:/Users/ejohnson/AppData/Roaming/Brackets/extensions/user/patlillis.show-whitespace-vs/main.js:302:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at Object.<anonymous> (file:///C:/Users/ejohnson/AppData/Roaming/Brackets/extensions/user/patlillis.show-whitespace-vs/main.js:323:13)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)

**Comment by patlillis** [comment]
Just a quick note, it looks like it's actually just a console warning, not an error. Still looking into fixing it though.

**Comment by patlillis** [comment]
This has been fixed in the GitHub repo. I will leave this issue open until the fix is deployed out to the extension in the registry.
